import Head from "next/head";
import styles from "../../styles/Home.module.css";
import {
  Image,
  Button,
  Grid,
  Input,
  Text,
  Link,
  Spacer,
  User,
} from "@nextui-org/react";
import { useRouter } from "next/router";
import { getUsersByClassName } from "../../lib/_utils";

function ClassUsers({ userData }) {
  console.log(userData);
  const router = useRouter();
  const { CID } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Class Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>StudyBuddies available in {CID}</h1>
        <Spacer y={2.5} />
        <div className={styles.grid} style={{ flexDirection: "column" }}>
          {/* {userData.map((user) => {
            let firstName = user.firstName;
            let lastName = user.lastName;
            let email = user.email;
            return (
              <>
                <User
                  src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                  name={firstName + " " + lastName}
                  description={email}
                />
              </>
            );
          })} */}
          <User
            src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
            name="Ariana Wattson"
            description="UI/UX Designer @Github"
          />
          <Spacer y={2.5} />
          <Text>
            <Link href="/signin">Already have an account?</Link>
          </Text>
          <Spacer y={2.5} />
          <Grid>
            <Link href="/survey">
              <Button size="xl" color="gradient" auto ghost>
                Create Account
              </Button>
            </Link>
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ben9543/MarinaHacks2022"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Ben Kweon, Janelle Chan, and Jordan Hilado
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Vercel Logo" width={20} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getInitialProps = async ({ params }) => {
  const courses = await getUsersByClassName(params.CID);
  let result = [];
  courses.forEach((doc) => {
    result.push(doc.data());
  });
  return {
    props: { userData: result },
  };
};

export default ClassUsers;
