import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Button,
  Grid,
  Input,
  Link,
  Text,
  Spacer,
  User,
} from "@nextui-org/react";

function Buddies() {
  return (
    <div className={styles.container}>
      <Head>
        <title>All StudyBuddies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>All StudyBuddies</h1>
        <Spacer y={2.5} />
        <User
          src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
          name="Ariana Wattson"
          description="UI/UX Designer @Github"
        />
        <div className={styles.grid} style={{ flexDirection: "column" }}>
          <Spacer y={2.5} />
          <Text>
            <Link href="/signup">Don't have an account?</Link>
          </Text>
          <Spacer y={2.5} />
          <Grid>
            <Button size="xl" color="gradient" auto ghost>
              Sign in
            </Button>
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ben9543/MarinaHacks2022"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Ben Kweon, Janelle Chan, and Jordan Hilado
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Vercel Logo" width={20} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Buddies;
