import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Grid, Input, Link, Text, Spacer } from "@nextui-org/react";

// Firebase imports
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../lib/_firebase.config";
import { useState } from "react";
import Router from 'next/router'
import { useEffect } from "react";
import { getCourses } from "../lib/_utils";

function Home({ courseData }) {
  const [isLoggedIn, setIsLoggedIn] = useState();
  const [searchTerm, setSearchTerm] = useState();
  onAuthStateChanged(auth, (user)=>{
    if (user) setIsLoggedIn(true);
    else setIsLoggedIn(false);
  });
  
  useEffect(()=>{
    if (isLoggedIn){ 
      Router.push("/");
    }
  },[isLoggedIn])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Homepage</h1>
        <Spacer y={2.5} />
        <input
          label="Search"
          placeholder="Name or class"
          onChange={(e)=>{
            setSearchTerm(e.target.value);
          }}
          value={searchTerm}
        />
        <Spacer y={2.5} />
        <Grid>
          <Button size="xl" shadow color="gradient" auto>
            Browse StudyBuddies
          </Button>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ben9543/MarinaHacks2022"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Ben Kweon, Janelle Chan, and Jordan Hilado
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Vercel Logo" width={20} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const courses = await getCourses();
  let result = []
  courses.forEach(doc=>{
    result.push(doc.data());
  })
  return {
    props: { courseData:result }
  }
}

export default Home;
