import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Grid, Input, Text, Link } from "@nextui-org/react";

function SignIn() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Sign Up</h1>
        <br />
        <div className={styles.grid} style={{ flexDirection: "column" }}>
          <Input size="xl" clearable bordered labelPlaceholder="First Name" />
          <Input size="xl" clearable bordered labelPlaceholder="Last Name" />
          <Input size="xl" clearable bordered labelPlaceholder="Email" />
          <Input.Password
            size="xl"
            clearable
            bordered
            labelPlaceholder="Password"
          />
          <Input.Password
            size="xl"
            clearable
            bordered
            labelPlaceholder="Confirm Password"
          />
          <br />
          Already have an account? Sign in
          <Link href="/signin">
            <Text>here</Text>
          </Link>
          <br />
          <Grid>
            <Button size="xl" color="gradient" auto ghost>
              Sign up
            </Button>
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default SignIn;
