import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Button,
  Radio,
  Grid,
  Input,
  Text,
  Link,
  Spacer,
} from "@nextui-org/react";

function Survey() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Tell us more!</h1>
        <Spacer y={2.5} />
        <Text h1>Select your college</Text>
        <Radio.Group value="A">
          <Radio value="A">College of the Arts</Radio>
          <Radio value="B">College of Business</Radio>
          <Radio value="C">College of Education</Radio>
          <Radio value="D">College of Engineering</Radio>
          <Radio value="E">College of Health and Human Services</Radio>
          <Radio value="F">College of Liberal Arts</Radio>
          <Radio value="G">College of Natural Sciences and Mathematics</Radio>
        </Radio.Group>
        <div className={styles.grid} style={{ flexDirection: "column" }}>
          <Spacer y={2.5} />
          <Input
            width="300px"
            size="xl"
            clearable
            bordered
            labelPlaceholder="Major"
          />
          <Spacer y={2} />
          <Input
            width="300px"
            size="xl"
            clearable
            bordered
            labelPlaceholder="Minor"
          />
          <Spacer y={2} />
          <Input
            width="300px"
            size="xl"
            clearable
            bordered
            labelPlaceholder="Discord Tag"
          />
          <Spacer y={2.5} />
          <Text>
            <Link href="/signin">Already have an account?</Link>
          </Text>
          <Spacer y={2.5} />
          <Link href="/home">
            <Grid>
              <Button size="xl" color="gradient" auto ghost>
                Continue
              </Button>
            </Grid>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ben9543/MarinaHacks2022"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Ben Kweon, Janelle Chan, and Jordan Hilado
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Vercel Logo" width={20} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Survey;
